#pragma config(Sensor, in1,    IR1,            sensorAnalog)
#pragma config(Sensor, in2,    IR2,            sensorAnalog)
#pragma config(Sensor, in3,    IR3,            sensorAnalog)
#pragma config(Sensor, in4,    IR4,            sensorAnalog)
#pragma config(Sensor, dgtl1,  gateEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LineTracking1,  sensorDigitalIn)
#pragma config(Sensor, dgtl4,  LineTracking2,  sensorDigitalIn)
#pragma config(Sensor, dgtl5,  LineTracking3,  sensorDigitalIn)
#pragma config(Sensor, dgtl6,  LineTracking4,  sensorDigitalIn)
#pragma config(Sensor, dgtl7,  LimitSwitchL,   sensorTouch)
#pragma config(Sensor, dgtl8,  LimitSwitchR,   sensorTouch)
#pragma config(Sensor, dgtl9,  Compass1,       sensorDigitalIn)
#pragma config(Sensor, dgtl10, Compass2,       sensorDigitalIn)
#pragma config(Sensor, dgtl11, Compass3,       sensorDigitalIn)
#pragma config(Sensor, dgtl12, Compass4,       sensorDigitalIn)
#pragma config(Motor,  port2,           vexGate,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           vexBaseR,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           vexBaseL,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//___________________________________________________________________________________________________

#include "utilities/searchUtilities.c"
#include "utilities/motorUtilities.c"
#include "utilities/transportUtilities.c"
#include "searchBall.c"
#include "moveBall.c"
#include "avoidBoundary.c"

//___________________________________________________________________________________________________

task boundary() {
	while (true) {
		isDetect();
	}
}

//___________________________________________________________________________________________________

task main(){

	// preparation command run here once
	moveForward(120, 3500);
	SensorValue(gateEncoder) = 0;

	// main program stream run here repeatedly
	while (true){
		startTask(boundary);
		if (!LineTrackTriggered) {
			stopRobot();
			searchWhateverInfront_version2();
			LineTrackTriggered = false;
		}
		if (ballCaptured == true) {
			stopTask(boundary);
			backToBox();
		}
		if (ballCaptured == false) {
			gateControl(0);
		}
	}
}

//___________________________________________________________________________________________________
